# Generated by Django 2.1 on 2019-12-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sent_Heard_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
