# Generated by Django 3.0.4 on 2020-05-04 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('author', models.CharField(default='', max_length=55)),
                ('title', models.CharField(default='', max_length=55)),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('author', models.CharField(default='', max_length=55)),
                ('title', models.CharField(default='', max_length=55)),
                ('description', models.TextField(default='', max_length=500)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('author', models.CharField(default='', max_length=55)),
                ('title', models.CharField(default='', max_length=55)),
                ('text_upload', models.FileField(default='', upload_to='text/')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('author', models.CharField(default='', max_length=55)),
                ('title', models.CharField(default='', max_length=55)),
                ('video', models.FileField(default='', upload_to='video/')),
            ],
        ),
    ]
