# Generated by Django 2.1 on 2019-11-28 04:29

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to='')),
            ],
        ),
    ]
