# Generated by Django 3.0.4 on 2020-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200505_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
    ]
