# Generated by Django 2.1 on 2019-12-04 04:41

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
