# Generated by Django 2.1 on 2019-12-05 04:18

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_audio_text_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.FileField(default='', storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='', storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='', storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
