# Generated by Django 2.1 on 2019-12-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191227_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text_typed',
        ),
    ]
