# Generated by Django 2.1 on 2019-12-05 21:10

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191205_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='', null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to='videos/', verbose_name=''),
        ),
    ]
