# Generated by Django 3.0.4 on 2020-07-19 23:57

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200621_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='audio/', validators=[posts.validators.validate_file_size_audio]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/', validators=[posts.validators.validate_file_size_photo]),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_upload',
            field=models.FileField(upload_to='text/', validators=[posts.validators.validate_file_size_text]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/', validators=[posts.validators.validate_file_size_video]),
        ),
    ]
