# Generated by Django 2.1 on 2019-12-05 21:45

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191205_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text',
        ),
        migrations.AddField(
            model_name='text',
            name='text_typed',
            field=models.TextField(default='', max_length=510),
        ),
        migrations.AddField(
            model_name='text',
            name='text_upload',
            field=models.FileField(default='', storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='', storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='django-static-sentheard'), upload_to=''),
        ),
    ]
