# Generated by Django 3.0.4 on 2020-07-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200719_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='text',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
