# Generated by Django 3.0.4 on 2020-07-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200720_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='text',
            name='description',
            field=models.TextField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default='', max_length=180),
        ),
    ]
