# Generated by Django 2.1 on 2019-12-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Published',
        ),
    ]
