# Generated by Django 3.0.4 on 2020-07-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200720_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text_upload',
            new_name='text',
        ),
    ]
