# Generated by Django 3.0.8 on 2020-08-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200728_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='text',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
