# Generated by Django 3.0.8 on 2020-08-10 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200810_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
