# Generated by Django 3.0.8 on 2020-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200811_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
