# Generated by Django 2.1 on 2019-12-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20191211_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
    ]
