# Generated by Django 3.0.8 on 2020-08-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20200811_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='description',
        ),
        migrations.AddField(
            model_name='audio',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
