# Generated by Django 3.0.8 on 2020-08-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20200812_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
