# Generated by Django 3.0.4 on 2020-04-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200323_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_paid',
            field=models.BooleanField(default=False, help_text='Designates whether the user has paid.', verbose_name='payment status'),
        ),
    ]
